baseURL = "https://carolineledbetter.us/"
languageCode = "en"                                   # website language
defaultContentLanguage = "en"                         # [en, zh, ...] determines which i18n file to use
title = "Caroline Ledbetter"                          # website title
theme = "LoveIt"
enableGitInfo = false                                 # whether to use git commit log to generate lastmod record
hasCJKLanguage = false                                # whether to include chinese/japanese/korean
paginate = 12                                         # default amount of posts in each pages
enableEmoji = true                                    # whether to use emoji code
enableRobotsTXT = true                                # whether to use robots.txt
googleAnalytics = ""                                  # [UA-XXXXXXXX-X] google analytics code
disqusShortname = "carolineledbetter-us"              # Disqus shortname to use Disqus in posts
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
                                                      # copyright description used only for seo schema
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.R"]


staticDir = ["static", "../assets/others"]            # static directories

[author]                                              #### Author Info
  name = "Caroline Ledbetter"

[sitemap]                                             #### Sitemap Info
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]                                          #### Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
  posts = ":year/:month/:slug/"

[menu]                                                #### Menu Info
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts"
    weight = 1
    
    [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "talks"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "tags"
    weight = 3

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "categories"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about"
    weight = 5


[params]
  version = "5.x"                                     # LoveIt theme version
  description = "Caroline's Webpage for Cool Stuff"   # site description
  keywords = ["Caroline Ledbetter", "R", "Blog"]      # site keywords

                                                      #### Home Page Info
  home_mode = "post"                                  # [post, other] home mode
  home_paginate = 6                                   # special amount of posts in each home post page
  avatar = "images/sealion.png"                       # URL of avatar shown in home page
  subtitle = "lessons learned along the way"          # subtitle shown in home page

  socialShare = true                                  # whether to show social share links in post page
  twitterImage = "logo.png"

# options for highlight.js (version, additional languages, and theme)
   highlightjsVersion = "9.12.0"
   highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
   highlightjsLang = ["r", "yaml"]
   highlightjsTheme = "atelier-heath-dark"
   highlightjsThemeDark = "color-brewer"

#### Footer CopyRight Info
  since = 2019                                        # Site creation time
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
                                                      # license info (HTML format is allowed)
  gitRepo = "https://github.com/ledbettc/caroline_r_blog"   
  # public git repo url to link lastmod git commit only then enableGitInfo is true

  linkToMarkdown = true                               # whether to show link to Raw Markdown content of the post

#### site verification code for Google/Bing/Yandex/Pinterest/Baidu
  google_verification = ""
  bing_verification = ""
  yandex_verification = ""
  pinterest_verification = ""
  baidu_verification = ""

#### CSS and JS Files CDN
  [params.cdn]               
    fontawesome_free_css = ''                         # for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
    animate_css = ''
    gitalk_css = ''
    gitalk_js = ''
    valine_js = ''
    jquery_js = ''
    lazysizes_js = ''
    smooth_scroll_js = ''
    katex_css = ''
    katex_js = ''
    katex_auto_render_js = ''
    mermaid_js = ''
    echarts_js = ''
    echarts_macarons_js = ''
    typeit_js = ''
    jquery_countdown_js = ''
    aplayer_css = ''
    aplayer_js = ''
    meting_js = ''

  [params.gravatar]                                   # Gravatar Info for preferred avatar in home page
    email = ""

  [params.social]                                     # Social Info in home page
    GitHub = "ledbettc"
    #Linkedin = "xxxx"
    Twitter = "@C_line_sealion"
    #Instagram = "xxxx"
    Email = "carolineledbetter@yahoo.com"
    #Facebook = "xxxx"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

  [params.share]                                      # Social Share Links in post page
    enable = true
    Twitter = true
    Facebook = true
    Reddit = true
    #Linkedin = true
    #Pinterest = true
    #HackerNews = true
    #Mix = true
    #Tumblr = true
    #VKontakte = true
    #Weibo = true

  [params.publisher]                                  # Publisher Info just for SEO
    name = "Caroline Ledbetter"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 105

  [params.logo]                                       # Website Log Info just for SEO
    url = "logo.png"
    width = 127
    height = 105

  [params.image]                                      # Website Image Info just for SEO
    url = "logo.png"
    width = 765
    height = 630

  [params.gitalk]                                     # Gittalk Comment Config (https://github.com/gitalk/gitalk)
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""

  [params.valine]                                     # Valine Comment Config (https://github.com/xCss/Valine)
    enable = false
    appId = ""
    appKey = ""
    notify = false
    verify = true
    avatar = "mp"
    placeholder = "Your comment ..."
    visitor = true
    recordIP = true

[privacy]                                             #### Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]                                          #### Options to make hugo output .md files.
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]                              #### Options to make hugo output .md files.
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]                                             #### Options to make hugo output .md files.
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
